[package]
name = "translator_test"
version = "0.1.0"
authors = ["Jeremy Mill <jeremy.mill@otis.com>"]

[dependencies]
translator = { path = "..\\Translator" }
libc = "0.2.30"

[lib]
crate-type = ["cdylib"]
